### ISSUE TITLE
Cannot build ml-api-adapter with current version of central-services-stream

### ISSUE THREAD

**Issue by kalinkrustev** [mojaloop/central-services-stream#140]
PR #133 changed Producer.isConnected() to require a parameter always.

This breaks the health check functionality in `ml-api-adapter`, where no parameter is passed to that function:
https://github.com/mojaloop/ml-api-adapter/blob/60aff84bcf234c4bab4fc2e982c84774c58e5fc2/src/lib/healthCheck/subServiceHealth.js#L49

**Comment by elnyry-sam-k** [comment]
Thanks for raising this @kalinkrustev , so whats the suggested way forward. Is there an issue to fix the regression or do we need one?

**Comment by kalinkrustev** [comment]
@aaronreynoza is working on a fix

**Comment by elnyry-sam-k** [comment]
cool, thank you!
